In [6]:
!pip3 install git+https://github.com/JustAnotherArchivist/snscrape.git

Collecting git+https://github.com/JustAnotherArchivist/snscrape.git
  Cloning https://github.com/JustAnotherArchivist/snscrape.git to /private/var/folders/rw/35py9_rs1z90r14f5srqkfg40000gn/T/pip-req-build-4t_vzmh0
  Running command git clone --filter=blob:none -q https://github.com/JustAnotherArchivist/snscrape.git /private/var/folders/rw/35py9_rs1z90r14f5srqkfg40000gn/T/pip-req-build-4t_vzmh0
  Resolved https://github.com/JustAnotherArchivist/snscrape.git to commit 59abeaf04c38c85b3afed3fb6b907a6868019877
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests[socks] in /Users/padmaprabagaran/opt/anaconda3/envs/sandbox/lib/python3.7/site-packages (from snscrape==0.4.3.20220107.dev64+g59abeaf) (2.22.0)
Requirement already satisfied: lxml in /Users/padmaprabagaran/opt/anaconda3/envs/sandbox/lib/python3.7/site-packages (from snscrape==0.4.3.20220107.dev64+g59abeaf) (4.5.0)
Requirement already satisfied: beautifulsoup4 in /Users/padmaprabagaran/opt/anaconda3/envs/sandbox/lib/python3.7/site-packages (from snscrape==0.4.3.20220107.dev64+g59abeaf) (4.8.2)
Requirement already satisfied: filelock in /Users/padmaprabagaran/opt/anaconda3/envs/sandbox/lib/python3.7/site-packages (from snscrape==0.4.3.20220107.dev64+g59abeaf) (3.0.12)
Requirement already satisfied: pytz in /Users/padmaprabagaran/opt/anaconda3/envs/sandbox/lib/python3.7/site-packages (from snscrape==0.4.3.20220107.dev64+g59abeaf) (2019.3)
ERROR: Package 'snscrape' requires a different Python: 3.7.6 not in '~=3.8'
WARNING: You are using pip version 21.3.1; however, version 22.2.2 is available.
You should consider upgrading via the '/Users/padmaprabagaran/opt/anaconda3/envs/sandbox/bin/python -m pip install --upgrade pip' command.

In [1]:
import snscrape.modules.twitter as sntwitter
import pandas as pd
import os
from datetime import date

In [33]:
def getData(keyword,year):
    tweets_list = []
    months = ['01','02','03','04','05','06','07','08','09','10','11','12']
    for x in months:
        print(x)
        for i,tweet in enumerate(sntwitter.TwitterSearchScraper(f'${keyword} since:{year}-{x}-01').get_items()):
            if i>299:
                break
            tweets_list.append([tweet.date, tweet.id, tweet.rawContent, tweet.user.username, tweet.user.verified, tweet.user.followersCount, tweet.user.location,tweet.replyCount, tweet.retweetCount, tweet.likeCount,tweet.media])

    # Creating a dataframe from the tweets list above
    tweets_df = pd.DataFrame(tweets_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username','Verified Status','Follower Count','Location','Reply Counts','Retweet Counts','Like Count','Media'])

    print('2021:'+str(len(tweets_df)))
    tweets_df.to_csv(f'data/{keyword}/{keyword}_{year}.csv',index=False)

In [34]:
getData('climatechange',2021)

01
02
03
04
05
06
07
08
09
10
11
12
2021:3600

In [24]:
data.iloc[0].Datetime

'2021-01-27 23:59:57+00:00'

In [35]:
data = pd.read_csv('data/climatechange/climatechange_2021.csv')
# data['Datetime'] = data['Datetime'].repalace(format="%Y/%m/%d") 
data = data.replace(regex=['\d{2}:\d{2}:\d{2}\+\d{2}:\d{2}'],value='')
data

,Datetime,Tweet Id,Text,Username,Verified Status,Follower Count,Location,Reply Counts,Retweet Counts,Like Count,Media
0,2022-09-12,1569444584333398016,@drdavidbull your co panellist Mr Anisiobi is ...,Tollingtonian,False,4,"Cambridge, England",0,0,0,NaN
1,2022-09-12,1569444555958927360,@ShaunGelling @DrHWeb @ManxShepherdess Don’t f...,ManxBirdLife,False,1562,"Laxey, Isle of Man",0,0,0,NaN
2,2022-09-12,1569444548123967488,"@RageSheen “Infection will end the pandemic”, ...",Dale13260598,False,340,Australian Capital Territory,0,0,0,NaN
3,2022-09-12,1569444541731868672,@WhangThe @HoraceHickling @RiXHD @UncleScorp @...,Snowcow79,False,192,NaN,0,0,0,NaN
4,2022-09-12,1569444530486923264,@Harry__Faulkner @TrueNorthCentre Trudeaus pla...,NancyH88480524,False,10,NaN,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3595,2022-09-12,1569440704413442048,"From the outside, it appears the Green Party o...",GadflyQuebec,False,4120,Canada Tiohtiak:ke,0,0,0,NaN
3596,2022-09-12,1569440699019571200,Day 1708\n#climatechange #climatecrisis #clima...,2000daysremain,False,0,NaN,0,0,0,[Photo(previewUrl='https://pbs.twimg.com/media...
3597,2022-09-12,1569440696452452352,@EdTheKat @Bhedin7 @MarkGerretsen the carbon t...,Nforesir,False,241,London ON Canada,0,0,0,NaN
3598,2022-09-12,1569440634137878528,'This is insanity': Pakistan's climate change ...,Ja1537Eddie,False,142,NaN,0,0,0,NaN
3599,2022-09-12,1569440617239048192,@LordAshcroft Climate change is down to brexit...,Jakderippa,False,1616,"England, United Kingdom",0,0,0,NaN

In [36]:
data.Datetime.unique()

array(['2022-09-12 '], dtype=object)

In [ ]:
# os.system(f"snscrape --since {from_date} twitter-search '{search_term} until:{end_date}' > result-tweets.txt")
# if os.stat("result-tweets.txt").st_size == 0:
#   counter = 0
# else:
#   df = pd.read_csv('result-tweets.txt', names=['link'])
#   counter = df.size

# print('Number Of Tweets : '+ str(counter))